<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" type="text/css" href="/public/style.css">
</head>

<body>
      @include("menu")
    <div class="contant">
      <div class="main-text col">
          <h1>Lorem ipsum</h1>
      </div>
      <div class="text-1">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquam laoreet est quis ullamcorper. Vivamus a justo ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras vitae tempor mi, id aliquam tellus. In iaculis venenatis elit eu facilisis. Nulla facilisi. Aliquam dictum ullamcorper nibh, quis egestas massa hendrerit et. Vivamus euismod fermentum blandit. Nulla vitae mi eget nunc bibendum ultrices. Suspendisse semper nec lorem quis interdum.
Phasellus interdum augue vel est varius ultricies. Donec pulvinar tortor ut faucibus vestibulum. Vivamus porta eleifend ligula, sit amet varius nulla finibus non. Donec vel augue mauris. Nulla velit metus, venenatis sit amet magna viverra, condimentum fringilla ligula. Etiam vestibulum nisl enim, eget congue ligula mattis nec. Ut eleifend tellus eget mauris blandit, at ultricies sapien volutpat. Sed pretium, neque vitae lobortis tristique, leo diam mattis felis, a lobortis dui quam vitae turpis. Ut in eleifend turpis. Praesent vitae nisi imperdiet erat tempor dignissim et at leo. Sed in felis erat. Sed convallis ullamcorper lacus vel dignissim. Cras iaculis, elit eget elementum commodo, lorem ex consequat orci, eu euismod sapien turpis sit amet tortor.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam cursus tincidunt lorem, a sodales diam. Cras egestas et tortor at laoreet. Quisque tortor diam, luctus sit amet tellus sit amet, fermentum laoreet mi. Vestibulum feugiat lacus sed arcu condimentum malesuada. Vivamus euismod risus et dignissim rhoncus. Etiam ipsum orci, faucibus vel ultricies eget, vestibulum quis quam. Praesent pharetra felis erat, vel convallis orci vehicula ac. Integer posuere, felis et malesuada porta, leo tellus commodo nibh, sed imperdiet quam neque vel nisi. Nunc egestas ullamcorper viverra. In at ultricies purus, sed lobortis neque.
Mauris vehicula mattis aliquam. Nulla facilisi. Nullam mollis, ante nec suscipit condimentum, neque neque auctor sapien, vel suscipit tellus est ac est. Vivamus tempus diam rutrum, eleifend justo eget, scelerisque mi. Duis nec nisl urna. Donec libero dui, dictum vitae justo et, sagittis posuere nulla. Praesent massa est, finibus a odio ut, mattis elementum leo. Nam tincidunt mollis libero, non gravida ipsum posuere eu. Integer sagittis ligula at porta rutrum.
Praesent est augue, interdum eget ipsum eu, cursus vehicula nibh. Pellentesque dignissim iaculis purus et ullamcorper. Mauris aliquet nunc sed sem vehicula, at placerat erat imperdiet. Etiam tempor efficitur erat eu fermentum. Aenean rhoncus, nisl in congue pretium, nibh tortor euismod ex, fringilla sodales mauris nulla nec eros. Nulla imperdiet, nibh et scelerisque luctus, urna lacus lacinia augue, in posuere augue mi non erat. Nullam tristique maximus volutpat. Duis ornare mauris elit, non convallis enim efficitur sit amet.
Duis vulputate viverra erat, vel rutrum nulla. Donec vitae nisi eget nunc suscipit fermentum. Nam euismod, libero at auctor sollicitudin, ex est hendrerit lacus, vel semper ex nisl vitae ligula. Phasellus in diam in risus tincidunt efficitur. Cras dui dui, dictum et rhoncus vel, venenatis sed tortor. Nam egestas ipsum sed vestibulum varius. Ut in ligula dolor. Cras tincidunt augue sit amet varius luctus. Cras egestas aliquam sodales. Nunc id euismod metus. Aenean sit amet dignissim urna. Etiam ac leo arcu. Nullam id vulputate ex.
Mauris volutpat vehicula sem in tincidunt. Morbi luctus, enim vitae hendrerit malesuada, ante massa volutpat ipsum, egestas tempus velit nisl id quam. Aliquam vitae egestas turpis, eu ultricies neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean tincidunt sapien et turpis convallis congue. Suspendisse magna odio, varius id lacinia et, pulvinar non tortor. Donec purus neque, tincidunt sit amet orci id, sagittis porta velit. Nulla ut sapien at erat eleifend tristique. Nam ullamcorper arcu vel ligula lobortis, sed sodales lectus molestie. Suspendisse arcu urna, ullamcorper sed lobortis id, cursus vel metus.
Vestibulum accumsan interdum urna et auctor. In et ex a neque rhoncus tempor. Curabitur aliquam fermentum dignissim. Nullam pulvinar vestibulum mauris nec gravida. Nam erat diam, lacinia ac felis a, convallis efficitur eros. Mauris viverra quam eget erat blandit mollis. Praesent eu mollis velit. Pellentesque condimentum erat ac sapien finibus, in semper orci venenatis. Maecenas vel dignissim nulla.
Ut vitae tortor quis velit vulputate consequat. Cras lectus lorem, facilisis nec lacinia sed, semper et velit. Donec pellentesque cursus tincidunt. Ut euismod mattis tortor ac efficitur. Cras consectetur libero dui, ac dignissim quam volutpat vitae. Praesent sit amet elit orci. Ut vitae neque in massa laoreet convallis sed et lorem. Donec varius lectus eget ultricies elementum.
Fusce convallis lacus quis odio blandit, cursus vehicula ex tincidunt. Donec mattis magna eu justo vestibulum ultricies eu at libero. Morbi semper lectus eros, pharetra sollicitudin mauris vulputate non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tristique magna ut posuere rhoncus. Fusce vel elit vel enim rhoncus laoreet a eget mauris. Aliquam porttitor ex sapien, a viverra arcu convallis nec. Donec vitae pretium quam.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent risus nisi, ullamcorper at luctus in, tempor id ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vel elit ac mauris hendrerit viverra quis in ex. Pellentesque et auctor justo. Cras iaculis arcu et nulla aliquam tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed condimentum lorem ut ante pulvinar placerat. Suspendisse posuere nisl lorem, quis aliquam elit volutpat eu. Integer vitae varius augue. Aenean aliquam ligula sed risus tincidunt, vel consequat urna imperdiet.
Maecenas arcu sem, auctor ac lacus a, consequat aliquam augue. Phasellus ut sagittis magna. Nam tempus porta orci tempus lacinia. Quisque eget ligula rutrum, mollis metus id, lacinia libero. Vestibulum nisl mi, consequat ut enim congue, posuere porta metus. Aliquam rutrum ultricies enim, et ornare turpis. Vivamus sit amet enim ultrices, aliquam nunc et, auctor tellus. Nam nibh massa, dictum sed nisl venenatis, tincidunt tincidunt odio.
Donec auctor dictum rutrum. Maecenas accumsan enim at felis blandit, ornare imperdiet libero semper. Sed condimentum facilisis ante, ac pellentesque neque vehicula ut. Sed vitae risus nec sem ultrices mattis non ac sapien. Fusce hendrerit augue sit amet ultricies accumsan. Donec pharetra at turpis ac interdum. Aenean in nisl at mauris elementum congue in aliquet risus. Sed pulvinar faucibus congue.
Duis semper diam eget nunc sollicitudin convallis. Sed ornare nunc a felis commodo, ac fringilla mauris maximus. Fusce neque magna, faucibus ac pharetra in, faucibus at quam. Maecenas consectetur augue sit amet cursus tristique. Cras dictum convallis quam, quis pharetra ex aliquam eget. Suspendisse tempus ipsum vitae lacinia porttitor. Maecenas ac ex nulla. Quisque varius blandit eleifend. Nulla mattis justo ut felis commodo, ac vulputate est pretium. Maecenas sed pharetra ante, quis egestas urna. Nulla aliquet nisl metus, eget vestibulum tellus commodo et. Aliquam tempor nulla nec tempor volutpat. Mauris quam ipsum, efficitur ut mattis vitae, viverra in mi. Integer eu massa libero. Curabitur ultrices ex id ante aliquam rhoncus. Curabitur eget varius ipsum, non pretium nisi.
Phasellus auctor nunc ac vestibulum tempor. Praesent nibh nisi, commodo vitae lacinia sed, placerat vel est. Curabitur tincidunt ipsum nisl, sed ullamcorper lectus varius quis. Quisque eleifend tempor erat, at molestie ligula maximus sit amet. Duis arcu ipsum, fermentum et mi quis, condimentum luctus nibh. Praesent vulputate, justo in fringilla eleifend, mauris dolor egestas libero, at placerat nunc lectus ac leo. Aenean lobortis viverra diam vitae aliquam. Etiam malesuada leo est, ac interdum nisl rhoncus a.</p>
      </div>
    </div>
  </div>
</body>
</html>